
server:
  port: 1002

#\u5E94\u7528\u540D\u79F0\u53CA\u9A8C\u8BC1\u8D26\u53F7
spring:
  application:
    name: lcn-pay


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcn-pay?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
# tm\u914D\u7F6E
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
