spring:
  application:
    name: cloud-zuul
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}